namespace Ralph.Core.Localization;

/// <summary>
/// Hardcoded English fallback strings. Used when no lang file is found.
/// Keys match those in lang/en.json.
/// </summary>
public static class EmbeddedStrings
{
    public static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // General
        ["app.name"] = "ralph",
        ["app.tagline"] = "ralph - PRD task loop runner",

        // Install
        ["install.welcome"] = "Welcome to ralph installer!",
        ["install.lang.question"] = "Choose your language / Escolha seu idioma:",
        ["install.lang.en"] = "English",
        ["install.lang.ptBR"] = "Português (Brasil)",
        ["install.dir.question"] = "Install directory:",
        ["install.dir.default"] = "(default: {0})",
        ["install.ui.question"] = "Preferred UI mode:",
        ["install.ui.none"] = "Plain terminal (always safe)",
        ["install.ui.spectre"] = "Spectre.Console (rich colors, progress bars)",
        ["install.ui.gum"] = "GUM (interactive prompts only)",
        ["install.ui.spectre_gum"] = "Spectre + GUM (full experience)",
        ["install.gum.detected"] = "GUM detected at: {0}",
        ["install.gum.not_found"] = "GUM not found in PATH.",
        ["install.gum.offer"] = "Install GUM now? (https://github.com/charmbracelet/gum)",
        ["install.gum.installing"] = "Installing GUM...",
        ["install.gum.install_ok"] = "GUM installed.",
        ["install.gum.install_fail"] = "GUM installation failed. Falling back to plain terminal.",
        ["install.gum.skip"] = "Skipping GUM installation.",
        ["install.copying"] = "Installing ralph to: {0}",
        ["install.ok"] = "Installed successfully.",
        ["install.path_added"] = "Added to user PATH. Restart your terminal to use 'ralph' from anywhere.",
        ["install.path_added_shell"] = "Added to PATH in shell rc file. Run: source ~/.bashrc (or ~/.zshrc)",
        ["install.path_manual_win"] = "To add to PATH manually: Settings → Advanced system settings → Environment Variables.",
        ["install.path_manual_unix"] = "To add to PATH, add to ~/.bashrc or ~/.zshrc:",
        ["install.path_export"] = "  export PATH=\"$PATH:{0}\"",
        ["install.fail"] = "Install failed: {0}",
        ["install.no_exe"] = "Could not determine executable path.",
        ["install.config_saved"] = "Preferences saved.",

        // Lang command
        ["lang.current"] = "Current language: {0}",
        ["lang.available"] = "Available languages:",
        ["lang.set_ok"] = "Language set to: {0}",
        ["lang.not_found"] = "Language '{0}' not found. Available: {1}",
        ["lang.update_checking"] = "Checking for language updates...",
        ["lang.update_ok"] = "Language files updated.",
        ["lang.update_fail"] = "Update failed: {0}",
        ["lang.update_none"] = "Already up to date.",
        ["lang.usage_set"] = "Usage: ralph lang set <code>  (e.g. en, ptBR)",
        ["lang.unknown_subcommand"] = "Unknown lang subcommand: {0}. Use: current, list, set, update",

        // UI command
        ["ui.current"] = "Current UI mode: {0}",
        ["ui.set_ok"] = "UI mode set to: {0}",
        ["ui.invalid"] = "Invalid UI mode '{0}'. Valid: none, spectre, gum, spectre+gum, tui",
        ["ui.toggled"] = "UI mode toggled to: {0}",
        ["ui.usage_set"] = "Usage: ralph ui set <mode>  (none|spectre|gum|spectre+gum|tui)",
        ["ui.unknown_subcommand"] = "Unknown ui subcommand: {0}. Use: current, set, toggle",
        ["ui.tui_fallback_reason"] = "  [!] TUI unavailable; using UI fallback. Reason: {0}",
        ["ui.tui_runtime_error"] = "[warn] TUI error: {0}",
        ["ui.tui_debug_log"] = "[warn] TUI debug log: {0}",

        // About
        ["about.title"] = "ralph - AI Task Loop Runner",
        ["about.version"] = "Version: {0}",
        ["about.author"] = "Author: Rodrigo Jager",
        ["about.github"] = "GitHub:   https://github.com/rodrigojager",
        ["about.linkedin"] = "LinkedIn: https://linkedin.com/in/rodrigojager",
        ["about.repo"] = "Repository: https://github.com/rodrigojager/ralph",
        ["about.license"] = "License: MIT",
        ["about.ralph_loop"] = "Ralph CLI: Implementation tool for the Ralph Wiggum autonomous iteration technique (Ralph Loops), proposed by Geoffrey Huntley (2025). https://ghuntley.com/ .",
        ["about.inspiration"] = "Features and implementation inspired by: https://github.com/agrimsingh/ralph-wiggum-cursor and https://github.com/michaelshimeles/ralphy",

        // Update
        ["update.checking"] = "Checking for updates...",
        ["update.current"] = "Current version: {0}",
        ["update.repo"] = "Release repository: {0}",
        ["update.repo_not_configured"] = "Release repository is not configured. Set RALPH_REPO=owner/repo or configure releaseRepo in ralph-config.json.",
        ["update.latest"] = "Latest version:  {0}",
        ["update.up_to_date"] = "Already up to date.",
        ["update.available"] = "Update available: {0} → {1}",
        ["update.downloading"] = "Downloading {0}...",
        ["update.applying"] = "Applying update...",
        ["update.lang_syncing"] = "Syncing language files...",
        ["update.lang_synced"] = "Language files synchronized ({0} file(s)).",
        ["update.lang_sync_skipped"] = "Language package not found in release (skipping language sync).",
        ["update.lang_sync_fail"] = "Language sync failed: {0}",
        ["update.ok"] = "Updated to {0}. Restart ralph to use the new version.",
        ["update.fail"] = "Update failed: {0}",
        ["update.no_asset"] = "No release asset found for this platform.",
        ["update.parse_release_fail"] = "Could not parse release info.",
        ["update.no_exe_path"] = "Cannot determine executable path.",
        ["update.looking_for"] = "  Looking for: {0}",
        ["update.available_assets"] = "  Available: {0}",

        // Init
        ["init.already"] = "Workspace already initialized at {0}",
        ["init.done"] = "Initialized ralph workspace at {0}",
        ["init.fail"] = "Init failed: {0}",

        // Run/Loop
        ["run.start"] = "Starting run loop...",
        ["run.task"] = "Task [{0}/{1}]: {2}",
        ["run.no_tasks"] = "No pending tasks found in PRD.",
        ["run.all_done"] = "All tasks completed.",
        ["run.gutter"] = "Gutter detected: engine is not making progress.",
        ["run.dry_run"] = "[DRY RUN] Would process {0} task(s):",
        ["run.dry_run_task"] = "  [{0}] {1}",
        ["run.dry_run_engine"] = "  Engine: {0} / Model: {1}",
        ["run.iteration"] = "Iteration {0}/{1}",
        ["run.status_iteration_engine"] = "Iteration {0} - engine: {1}",
        ["run.tests_running"] = "Running tests...",
        ["run.tests_ok"] = "Tests passed.",
        ["run.tests_fail"] = "Tests failed.",
        ["run.lint_running"] = "Running lint...",
        ["run.lint_ok"] = "Lint passed.",
        ["run.lint_fail"] = "Lint failed.",
        ["run.retrying"] = "Retrying ({0}/{1})...",
        ["run.engine_start"] = "Calling engine: {0}",
        ["run.engine_done"] = "Engine finished in {0:F1}s",
        ["run.no_changes"] = "Engine reported success but no file changes detected.",
        ["run.no_change_marked_for_review"] = "Task marked as [~] for manual review. Continuing to the next task.",
        ["run.branch_create"] = "Creating branch: {0}",
        ["run.branch_fail"] = "Could not create branch (not a git repo?). Continuing without branch.",
        ["run.commit"] = "Committing changes...",
        ["run.push"] = "Pushing branch...",
        ["run.pr_create"] = "Creating pull request...",
        ["run.pr_ok"] = "Pull request created.",
        ["run.not_git"] = "Not a git repo; skipping branch/PR.",
        ["run.tokens"] = "[tokens] in={0} out={1} total={2}",
        ["run.session_tokens"] = "Session total: in={0} out={1} total={2} tokens",
        ["run.branch_mode_disabled"] = "--branch-per-task: not a git repo, branching disabled.",
        ["run.summary_complete"] = "Summary: {0}/{1} tasks done in {2} iterations.",
        ["run.summary_partial"] = "Summary: {0}/{1} tasks done.",
        ["run.branch_created"] = "Branch: {0}",
        ["run.branch_create_failed"] = "Could not create branch '{0}', continuing on current branch.",
        ["run.fallback_engine"] = "Fallback engine: '{0}'",
        ["run.no_output_hint"] = "(No output. Is command '{0}' in PATH? Try: ralph doctor)",
        ["run.max_iterations_pending"] = "Max iterations reached with pending tasks.",
        ["run.dry_run_all_completed"] = "  (all tasks already completed)",
        ["run.dry_run_no_files"] = "No files will be modified (dry run).",
        ["run.done_duration"] = "Done. ({0:F1}s)",
        ["run.engine_not_found"] = "Engine '{0}' not found. Registered: {1}",
        ["run.engine_failed_task"] = "{0} [{1}/{2}] \"{3}\" (exit {4})",
        ["run.engine_failed_with_log"] = "Engine '{0}' failed (exit code {1}). See .ralph/errors.log",
        ["run.gutter_details"] = "GUTTER: no progress after {0} attempts. Details in .ralph/errors.log",
        ["run.engine_exit_stopping"] = "Engine exited with code {0}. Stopping.",
        ["run.lint_failed_not_marked"] = "Lint failed. Task not marked complete.",
        ["run.tests_failed_not_marked"] = "Tests failed. Task not marked complete.",
        ["run.browser_failed_not_marked"] = "Browser validation failed. Task not marked complete.",
        ["run.push_failed_local_commit"] = "Push failed for branch '{0}'. Commit is local.",
        ["run.pr_creation_failed"] = "PR creation failed. Is 'gh' installed and authenticated?",
        ["run.engine_failed"] = "Engine '{0}' failed (exit code {1}).",
        ["run.context_signal_warn"] = "Context signal: {0}. Current total tokens: {1}.",
        ["run.context_signal_rotate"] = "Context rotation requested (ROTATE). Continuing with fresh iteration context.",
        ["run.context_signal_defer"] = "Context deferral requested (DEFER). Stopping this run to avoid context rotting.",
        ["run.context_signal_gutter"] = "Context gutter signal detected (GUTTER). Stopping run.",
        ["run.no_change_fail_fast"] = "No-change policy is fail-fast. Stopping run.",
        ["run.manual_review_remaining"] = "Some tasks were marked as [~] and require manual review.",
        ["run.status_all_tasks_completed"] = "All tasks completed",
        ["run.status_creating_branch"] = "Creating branch {0}...",
        ["run.status_engine_not_found"] = "Engine '{0}' not found",
        ["run.status_engine_attempt_exit"] = "Engine '{0}' attempt {1} exit code {2}",
        ["run.status_gutter"] = "GUTTER detected",
        ["run.status_stopped_exit_code"] = "Stopped after engine exit code {0}",
        ["run.status_no_workspace_changes"] = "No workspace changes detected",
        ["run.status_running_lint"] = "Running lint...",
        ["run.status_lint_failed"] = "Lint failed",
        ["run.status_tests_failed"] = "Tests failed",
        ["run.status_browser_failed"] = "Browser validation failed",
        ["run.status_completed_task"] = "Completed task {0}/{1}",
        ["run.status_skipped_task_review"] = "Skipped task {0}/{1} for manual review",
        ["run.status_committing"] = "Committing...",
        ["run.status_pushing"] = "Pushing...",
        ["run.status_creating_pr"] = "Creating PR...",
        ["run.status_max_iterations_pending"] = "Max iterations reached with pending tasks",
        ["run.status_max_iterations"] = "Max iterations reached",
        ["run.status_running_engine"] = "Running: {0}",
        ["run.status_task_completed"] = "Task completed",
        ["run.status_spinner"] = "[spin] {0} {1}",
        ["cursor.output.current_task"] = "Current task",
        ["cursor.output.success"] = "Success",
        ["cursor.output.error"] = "Error",

        // Once
        ["once.start"] = "Running single task...",
        ["once.brownfield"] = "Brownfield mode: {0}",

        // Tasks
        ["tasks.list_header"] = "Tasks in {0}:",
        ["tasks.none"] = "No tasks found.",
        ["tasks.next"] = "Next task: [{0}] {1}",
        ["tasks.done_ok"] = "Marked task {0} as done.",
        ["tasks.done_summary"] = "{0}/{1} tasks done",
        ["tasks.done_fail"] = "Could not mark task as done.",
        ["tasks.sync_start"] = "Syncing GitHub issues from {0}...",
        ["tasks.sync_ok"] = "Synced {0} issue(s) to {1}",
        ["tasks.sync_fail"] = "Sync failed: {0}",
        ["tasks.usage"] = "Usage: ralph tasks <list|next|done|sync>",
        ["tasks.usage_done"] = "Usage: ralph tasks done <next|index>",
        ["tasks.sync.usage"] = "Usage: ralph tasks sync --repo owner/repo [--label NAME] [--state open|closed|all] [--output PATH] [--force]",
        ["tasks.sync.invalid_state"] = "Invalid --state. Use: open, closed, all",
        ["tasks.sync.output_exists"] = "Output already exists: {0}. Use --force to overwrite.",

        // Config
        ["config.list_header"] = "Configuration ({0}):",
        ["config.get_key"] = "{0} = {1}",
        ["config.set_ok"] = "Set {0} = {1}",
        ["config.key_not_found"] = "Key not found: {0}",
        ["config.empty"] = "(no engine config)",
        ["config.not_set"] = "(not set)",
        ["config.unknown_key"] = "(unknown key)",
        ["config.unknown_key_named"] = "Unknown key: {0}",
        ["config.invalid_int"] = "Invalid integer value",
        ["config.invalid_float"] = "Invalid numeric value",
        ["config.invalid_bool"] = "Invalid boolean value. Use: true or false",
        ["config.invalid_context_rotation_mode"] = "Invalid context rotation mode. Use: warn, rotate, defer, gutter",
        ["config.invalid_no_change_policy"] = "Invalid no-change policy. Use: fallback, retry, fail-fast",
        ["config.invalid_parallel_integration"] = "Invalid parallel integration strategy. Use: merge, create-pr, no-merge",
        ["config.usage"] = "Usage: ralph config list|get|set [key] [value]",
        ["config.usage_get"] = "Usage: ralph config get <key>",
        ["config.usage_set"] = "Usage: ralph config set <key> <value>",

        // Logs
        ["logs.tail_header"] = "Logs ({0}):",
        ["logs.no_logs"] = "No log entries found.",
        ["logs.follow_all_unsupported"] = "--follow with --level all is not supported. Use: info or error.",
        ["logs.usage"] = "Usage: ralph logs tail [--follow] [--level info|error|all] [--since ISO-8601]",
        ["report.usage"] = "Usage: ralph report last",
        ["report.none"] = "No report found yet.",

        // Doctor
        ["doctor.header"] = "ralph doctor",
        ["doctor.separator"] = "------------",
        ["doctor.workspace_ok"] = "  [OK] Workspace initialized",
        ["doctor.workspace_missing"] = "  [!] Workspace not initialized (run: ralph init)",
        ["doctor.prd_ok"] = "  [OK] PRD file found: {0}",
        ["doctor.prd_missing"] = "  [!] PRD file not found",
        ["doctor.engine_ok"] = "  [OK] Engine in PATH: {0}",
        ["doctor.engine_missing"] = "  [!] Engine not available: {0} ({1})",
        ["doctor.engine_auth_required"] = "  [!] Engine needs login: {0}",
        ["doctor.engine_auth_hint"] = "  [i] {0}",
        ["doctor.engine_auth_prompt"] = "Open authentication docs in browser? [y/N] ",
        ["doctor.git_ok"] = "  [OK] Git repo detected",
        ["doctor.git_missing"] = "  [i] Not a git repo",
        ["doctor.git_unknown"] = "  [i] git status unknown",
        ["doctor.gum_ok"] = "  [OK] GUM detected: {0}",
        ["doctor.gum_missing"] = "  [i] GUM not found in PATH",
        ["doctor.git_init_prompt"] = "Initialize a Git repository in this directory now? [y/N] ",
        ["doctor.git_init_ok"] = "  [OK] Git repository initialized.",
        ["doctor.git_init_fail"] = "  [!] Failed to initialize Git repository.",
        ["doctor.git_init_aborted"] = "  [i] Git initialization skipped.",
        ["doctor.git_init_skipped_non_interactive"] = "  [i] Non-interactive mode: skipping Git initialization prompt.",
        ["doctor.git_commit_ok"] = "  [OK] Initial Git commit created.",
        ["doctor.git_commit_skipped"] = "  [i] Initial commit was not created automatically.",
        ["doctor.process_header"] = "Process snapshot:",
        ["doctor.process_unavailable"] = "  [i] Process listing is unavailable on this platform.",
        ["doctor.process_none"] = "  [OK] No matching processes found.",
        ["doctor.process_count"] = "  [i] Matching processes: {0}",
        ["doctor.process_item"] = "    pid={0} name={1} started={2}",

        // Clean
        ["clean.confirm"] = "Delete .ralph/ workspace at {0}? [y/N] ",
        ["clean.done"] = "Cleaned workspace at {0}",
        ["clean.aborted"] = "Aborted.",
        ["clean.not_found"] = "No workspace found at {0}",
        ["clean.force_required"] = "Use --force to remove .ralph/ and reset state.",
        ["clean.nothing"] = "Nothing to clean.",
        ["clean.fail"] = "Clean failed: {0}",

        // Rules
        ["rules.list_header"] = "Guardrails ({0}):",
        ["rules.empty"] = "(no guardrails defined)",
        ["rules.added"] = "Added rule: {0}",
        ["rules.cleared"] = "Guardrails cleared.",
        ["rules.clear_confirm"] = "Clear all guardrails? [y/N] ",
        ["rules.force_required"] = "Use --force to clear all guardrails.",
        ["rules.usage"] = "Usage: ralph rules <list|add|clear> [text] [--force]",
        ["rules.usage_add"] = "Usage: ralph rules add \"rule text\"",

        // Parallel
        ["parallel.start"] = "Running {0} tasks with max parallelism = {1}...",
        ["parallel.no_tasks"] = "No tasks to run in parallel.",
        ["parallel.failed_task"] = "[parallel] failed: {0}",
        ["parallel.summary"] = "Parallel finished: {0} succeeded, {1} failed",
        ["parallel.dry_run"] = "[DRY RUN] Tasks planned for parallel execution:",
        ["parallel.retry_failed"] = "Retrying only failed tasks ({0})...",

        // Errors
        ["error.prd_not_found"] = "PRD file not found at {0}",
        ["error.prd_not_found_hint"] = "PRD file not found at {0}. Pass a task directly: ralph once \"your task\"",
        ["error.unknown_command"] = "Unknown command: {0}",
        ["error.usage"] = "Usage: ralph <init|setup|run|loop|once|parallel|install|config|tasks|logs|doctor|clean|rules|lang|ui|about|update|report> [options]. Use ralph --help for details.",
        ["error.unhandled"] = "Unhandled error: {0}",
        ["error.invalid_flag_typo"] = "Unknown option '{0}'. Did you mean '{1}'?",
        ["run.cancel_requested"] = "Cancellation requested (Ctrl+C). Stopping safely...",
        ["run.force_exit_requested"] = "Force exit requested. Exiting now.",
        ["run.operation_canceled"] = "Operation canceled.",

        // TUI dashboard
        ["tui.panel.status"] = "Status",
        ["tui.panel.tokens"] = "Tokens",
        ["tui.panel.activity_log"] = "Activity Log",
        ["tui.panel.progress"] = "Progress",
        ["tui.panel.errors"] = "Errors",
        ["tui.panel.engine_output"] = "Engine Output",
        ["tui.tokens_template"] = "in:    {0}\nout:   {1}\ntotal: {2}\nctx:   {3}",
        ["tui.status.starting"] = "Starting...",
        ["tui.status.completed"] = "Completed \u2014 Press [Q] to exit",
        ["tui.shortcut.fallback"] = "[F5] Fallback",
        ["tui.shortcut.quit"] = "[Q] Quit",
        ["tui.shortcut.page_up"] = "[PgUp] Scroll Up",
        ["tui.shortcut.page_down"] = "[PgDn] Scroll Down",
        ["tui.shortcut.home"] = "[Home] Top",
        ["tui.shortcut.end"] = "[End] Latest",
        ["tui.shortcut.copy"] = "[C] Copy Panel",
        ["tui.copy.ok"] = "Panel content copied to clipboard.",
        ["tui.copy.empty"] = "Nothing to copy in this panel.",
        ["tui.copy.fallback_file"] = "Clipboard unavailable. Saved panel content to: {0}",

        // Help
        ["help.header"] = "ralph - PRD task loop runner",
        ["help.full"] = "\nUSAGE\n  ralph <command> [options]\n\nWORKSPACE\n  ralph init [--force]                  Initialize .ralph/ workspace in current directory\n  ralph clean [--force]                 Remove .ralph/ workspace\n  ralph doctor [--yes|--non-interactive]\n                                        Check workspace, PRD, engines and PATH\n                                        Offer git init when outside a repository\n\nRUNNING TASKS\n  ralph run   [options]                 Run all pending PRD tasks in a loop\n  ralph loop  [options]                 Alias for run\n  ralph once  [\"task\"] [options]        Run one PRD task (or a one-off task without PRD)\n  ralph parallel [\"task\" ...] [options] Run tasks concurrently (or all pending PRD tasks)\n\nRUN OPTIONS\n  --prd PATH              Path to PRD file (default: PRD.md in cwd)\n  --engine NAME           Engine to use (cursor, claude, codex, opencode, qwen, droid, copilot, gemini)\n  --model NAME            Model override\n  --sonnet                Shortcut: engine=claude model=claude-sonnet-4-6\n  --opus                  Shortcut: engine=claude model=claude-opus-4-6\n  --haiku                 Shortcut: engine=claude model=claude-haiku-4-5\n  --max-iterations N      Stop after N iterations\n  --max-parallel N        Max workers for 'parallel' (default: 2)\n  --retry-failed          Re-run only failed tasks once in 'parallel'\n  --parallel-integration <merge|create-pr|no-merge>\n                          Post-parallel integration strategy\n  --max-retries N         Max retries per task\n  --retry-delay SEC       Seconds between retries\n  --max-tokens N          Token limit passed to engine\n  --temperature T         Temperature passed to engine\n  --skip-tests            Skip test execution after each task\n  --no-lint / --skip-lint Skip lint execution\n  --fast                  Skip both tests and lint\n  --dry-run               Preview execution without running engine\n  --debug-engine-json     Save raw engine result snapshots to .ralph/debug/engine-json/\n  --verbose / -v          Show engine prompt, stdout and timing\n  --branch-per-task       Create a git branch for each task\n  --base-branch NAME      Base branch for new task branches (default: current)\n  --create-pr             Push and open a GitHub PR after each task\n  --draft-pr              Create PR as draft (implies --create-pr)\n  --auto-rollback         Auto-rollback task changes on failure\n  -- ...args              Pass remaining args directly to the engine\n\nTASKS\n  ralph tasks list [--prd PATH]         List all tasks\n  ralph tasks next [--prd PATH]         Show next pending task\n  ralph tasks done <n> [--prd PATH]     Mark task N as done\n  ralph tasks sync --repo owner/repo    Sync GitHub issues -> PRD\n    [--label NAME] [--state open|closed|all] [--output PATH] [--force]\n\nCONFIG\n  ralph config list [--prd PATH]        Show all config values\n  ralph config get <key>                Get a config value\n  ralph config set <key> <value>        Set a config value\n\nRULES\n  ralph rules list                      List guardrails\n  ralph rules add \"rule text\"           Add a guardrail\n  ralph rules clear [--force]           Clear all guardrails\n\nLOGS\n  ralph logs tail [--follow] [--level info|error|all] [--since ISO-8601]\n\nREPORTS\n  ralph report last                     Show latest execution report\n\nINSTALL & UPDATE\n  ralph install [DIR]                   Install ralph globally (asks language/UI)\n  ralph update                          Self-update to the latest release\n\nLANGUAGE & UI\n  ralph lang current                    Show current language\n  ralph lang list                       List available languages\n  ralph lang set <code>                 Change language (e.g. en, ptBR)\n  ralph lang update                     Update language files\n  ralph ui current                      Show current UI mode\n  ralph ui set <mode>                   Set UI mode (none|spectre|gum|spectre+gum|tui)\n  ralph ui toggle                       Cycle through UI modes\n  --ui <mode>                           Override UI mode for this invocation\n  RALPH_UI=none ralph ...               Emergency fallback to plain terminal\n\nOTHER\n  ralph about                           About ralph and author\n  ralph --version / -V                  Show version\n  ralph --help / -h                     Show this help",
    };
}
